### ISSUE TITLE
New GA tracking requirements  - MAS employee can see GA reports for the Mortgage Calculator

### ISSUE THREAD

**Issue by KKConsultantBA** [moneyadviceservice/mortgage_calculator#62]
As a MAS employee I want to be able to use Google Analytics to assess the performance of the Mortgage calculator, so that I can see how the tools are performing against three key performance indicators (KPIs)

KPI 1 - Number of completions. 
- [ ] When a homebuyer, adds valid data into the
- [ ] ·         X property price (Page 1 field)
- [ ] ·         Z mortgage length (Page 1 field)
  fields in the mortgage calculator, then fire a tracking event to confirm that an activity that qualifies as a completion of the Mortgage calculator tool has taken place.

Code / instructions from Periscopix:
- [ ] The following GA tracking code should be executed upon the user having interacted with the above mentioned fields and submitting their entry –
  _gaq.push(['_trackEvent','Mortgage Calculator','Completion','Click']);

Refinements / adjustments to values
- [ ] When any refinement is made to any/all of:
- [ ] Property price
- [ ] Deposit
- [ ] mortgage term
- [ ] Interest rate
  Then, log this so we can see whether users attempt to adjust the sliders once they have been presented with an initial mortgage calculation.
- [ ] Capture the number of visitors that progress to page 3 - the next steps / advice page

---

REMOVED
- [ ] ·         Y interest rate (removed as previous discussions were based on an old design. Interest rate is a page 2 field now)
