### ISSUE TITLE
GA tracking  - MAS employee can see GA reports for the Stamp Duty Calculator

### ISSUE THREAD

**Issue by KKConsultantBA** [moneyadviceservice/mortgage_calculator#76]
As a MAS employee I want to be able to use Google Analytics to assess the performance of the Stamp Duty calculator so that I can see how the tools are performing against selected key performance indicators (KPIs)

KPI 1 - Number of completions. 
- [ ] When a homebuyer enters the price of the property into the property price field, then fire a tracking event to confirm that an activity that qualifies as a completion of the Stamp duty calculator tool has taken place.

Code / instructions from Periscopix:
- [ ] The following GA tracking code should be executed upon the user having interacted with the property value field and submitting their entry –
  _gaq.push(['_trackEvent','Stamp Duty Calculator','Completion','Click']);

Refinements / adjustments to values
- [ ] When any refinement is made to the:
  Property price
  Then, log this so we can see whether users attempt to adjust the sliders once they have been presented with an initial stamp duty value.
- [ ] Capture the number of visitors that progress to page 3 - the next steps / advice page
